apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-genai-frontend
  namespace: bae-recipe
  labels:
    app: aws-genai-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-genai-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: aws-genai-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/teamshackathon/prod/aws-genai-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi